- name: Lamp Setup
  hosts: testvm
  become: yes
  become_method: sudo
  tasks:
      - name: update
        apt: 
          update_cache: yes   

      - name: Installing apache
        apt:
          name: apache2
          state: latest

      - name: Removing site files
        file:
          path: "{{ item }}"
          state: absent
        with_items: 
          - /etc/apache2/sites-available/000-default.conf
          - /var/www/html/index.html

      - name: Copy files
        copy:
          src: "{{ item.confsrc }}"
          dest: "{{ item.confdest }}"
        with_items: 
          - { confsrc: '/home/cloudstack/Apache-yaml/etc/apache2/sites-available/000-default.conf', confdest: '/etc/apache2/sites-available/'}
          - { confsrc: '/home/cloudstack/Apache-yaml/var/www/html/index.html', confdest: '/var/www/html/'}

      - name: Starting service apache2
        service:
          name: apache2
          state: started 

      - name: Getting the status of the service
        shell: systemctl status apache2 | grep 'since'
        register: status

      - debug:
          var: status.stdout 