- name: Joomla Setup
  hosts: localhost
  tasks:
      - name: Restarting sshd
        shell: "sed -i 's/#Match User anoncvs/ForceCommand echo Please wait until the installation is completed..../g' /etc/ssh/sshd_config && systemctl restart sshd"

      - name: Updating Packages
        ansible.builtin.apt:
          update_cache: yes

      - debug:
         msg: "Installing OpenLitespeed"

      - name: Installing OpenLitespeed RPM
        shell: wget -O - http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | sudo bash

      - name: Installing OpenLitespeed
        apt:
          name: openlitespeed
          state: latest

      - name: Starting service OpenLitespeed
        service:
          name: lsws
          state: started 

      - name: Getting the status of the service
        shell: systemctl status lsws | grep 'since'
        register: status

      - debug:
          var: status.stdout 

      - name: Creating a directory for OpenLitespeed
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory     
          recurse: yes
        with_items:
            - /var/www/html
            - /usr/local/lsws/conf/vhosts/joomla

      - name: Creating a Virtualhost file for OpenLitespeed
        ansible.builtin.file:
          path: /usr/local/lsws/conf/vhosts/joomla/vhconf.conf
          state: touch     

      - name: Change ownership of a directory
        ansible.builtin.file:
          path: /usr/local/lsws/conf/vhosts/joomla
          state: directory
          recurse: yes
          owner: lsadm
          group: nogroup
